# Profile information
name: Fresh
title: Fresh - Free Jekyll Theme
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/fresh" # the subpath of your site, e.g. /blog
url: "artemsheludko.pw" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
